---
- name: Install dependencies
  apt: name={{ item }} state=latest
  with_items:
    - python
    - curl
    - apt-transport-https
    - ca-certificates
    - apparmor

- name: adding apt-key
  shell: curl -sSL https://get.docker.com/gpg | apt-key add -

- name: docker package
  shell: curl -sSL https://get.docker.com/ | sh

- name: install pip
  shell: which pip || curl -sSL https://bootstrap.pypa.io/get-pip.py | python

- name: install docker-compose
  pip: name=docker-compose state=present

# docker-py need to install after docker-compose since ansible docker_container module still has a stupid bug with docker-py version
# using docker-py==1.8.1 is only our option
- name: install docker-py
  pip: name=docker-py version=1.8.1 state=present
